[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.16", features = ["v4"] }
chrono = { version = "0.4", features = ["serde", "clock"] }
thiserror = "1.0"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
